name: Secret Scan
on: [push, pull_request, workflow_dispatch]
jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Gitleaks scan
        uses: zricethezav/gitleaks-action@v2
        with:
          args: detect --source . --redact
