# ======================================================================
# FILE: ansible/collections/requirements.yml
# ======================================================================
collections:
  - name: azure.azcollection
