# ======================================================================
# FILE: terraform/cloud-init/web.yaml
# ======================================================================
#cloud-config
package_update: true
packages:
  - nginx
write_files:
  - path: /var/www/html/index.html
    permissions: '0644'
    content: |
      <html><head><title>Project 7</title></head>
      <body>
        <h1>Azure HA Web on Hub-Spoke + VMSS</h1>
        <p>Host: {{ ds.meta_data.local_hostname }}</p>
      </body></html>
runcmd:
  - systemctl enable --now nginx
