apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/chadalanlester/showcase.git
    targetRevision: main
    path: project-1-multicloud-gitops/k8s-manifests/app
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [ CreateNamespace=true ]
