apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: trivia-api-hpa
  namespace: resilient
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: trivia-api
  minReplicas: 2
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: { type: Utilization, averageUtilization: 60 }
