---
name: Security Scans
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy_fs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy filesystem scan
        run: |
          docker run --rm -v "$PWD:/wrk" aquasec/trivy:0.54.1 \
            filesystem --exit-code 0 --no-progress --format table --output /wrk/trivy-fs.txt /wrk
      - uses: actions/upload-artifact@v4
        with:
          name: trivy-fs
          path: trivy-fs.txt
          retention-days: 7

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tfsec scan
        run: |
          docker run --rm -v "$PWD/terraform:/src" aquasec/tfsec:latest /src --soft-fail
