name: TF Apply (Project 3)
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths: [ "project-3-secure-oidc-terraform/**" ]
permissions:
  id-token: write
  contents: read
jobs:
  apply:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: project-3-secure-oidc-terraform/terraform } }
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false
